"""adds completion rate target

Revision ID: b8648e7721f9
Revises: f280953e34dd
Create Date: 2023-07-24 18:57:39.129525

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b8648e7721f9"
down_revision = "f280953e34dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("habits", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("completion_rate_target", sa.Numeric(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("habits", schema=None) as batch_op:
        batch_op.drop_column("completion_rate_target")

    # ### end Alembic commands ###
