"""add relationship

Revision ID: f09c865ad2ba
Revises: 
Create Date: 2023-06-25 16:44:59.480365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f09c865ad2ba"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "habits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("interval_type", sa.String(), nullable=True),
        sa.Column("interval_value", sa.Integer(), nullable=True),
        sa.Column("day_of_week", sa.String(), nullable=True),
        sa.Column("repetition_type", sa.String(), nullable=True),
        sa.Column("repetition_value", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "todos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("original_scheduled_date", sa.Date(), nullable=True),
        sa.Column("current_scheduled_date", sa.Date(), nullable=True),
        sa.Column("done_date", sa.Date(), nullable=True),
        sa.Column("habit_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["habit_id"],
            ["habits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("todos")
    op.drop_table("habits")
    op.drop_table("users")
    # ### end Alembic commands ###
